### PR TITLE
[WIP] Add Windows Registration

### PR DESCRIPTION
**Pull request by guillaumelecerf**
- [ ] do in situ tests

### CODE REVIEW

**Comment by shiroko** [comment]
In my understanding, the X-WNS-Type is mandatory for the template registration for Windows Notification Service.

 Is my understanding incorrect?

**Comment by guillaumelecerf** [comment]
This commit is about registration, not notification (see https://msdn.microsoft.com/en-us/library/dn223265.aspx).
But as stated, I have to test it with a real windows device.

**Comment by shiroko** [comment]
Yeah.
I think it is better to override appendAdditionalNode() method to be able to add the WnsHeaders tag.

**Comment by shiroko** [comment]
merged it for now. thanks.

**Pull request merged**
