### PR TITLE
Add support for scheduled notifications

### PR DESCRIPTION
**Pull request by guillaumelecerf**
TODO:
- [ ] ~~test with a device~~

### CODE REVIEW

**Comment by guillaumelecerf** [comment]
My "free" tier does not allow me to send scheduled notifications, so I'm unable to test my code :(

**Comment by shiroko** [comment]
My tire is "free", too.
API reference does not say about this feature.
I can see it only in "azure-notificationhubs-java-backend" code, and I think this patch is probably OK.
Would you like me to merge this for now ?

**Comment by guillaumelecerf** [comment]
I think the code is rather clean and failsafe to be merged, so yes, please merge it.

**Comment by shiroko** [comment]
Merged it, thanks.

**Comment by guillaumelecerf** [comment]
Thanks.

**Pull request merged**
