### PR TITLE
Fix NotificationHub::updateRegistration: ETag is not mandatory when c…

### PR DESCRIPTION
**Pull request by guillaumelecerf**
…reating a new registration

### CODE REVIEW

**Comment by guillaumelecerf** [comment]
@shiroko : gentle ping

**Comment by shiroko** [comment]
Sorry for being late.

NotificationHub::updateRegistration is for "Update Registration" API(https://msdn.microsoft.com/en-us/library/dn223262.aspx) .
NotificationHub::createRegistration should be used when creating a new registration.

Update Registration API document does not say Etag is optional.

**Comment by guillaumelecerf** [comment]
OK, but there is a "create or update" method (https://msdn.microsoft.com/en-us/library/dn495630.aspx)  and the only difference is that in "create" the ETag is mandatory, whereas in "create or update" it is not.

My workflow is:
- get a registrationId with createRegistrationId (https://msdn.microsoft.com/en-us/library/dn495626.aspx)
- create or update it

Your comment states "Create or Update Registration", so we either have to modify the comment to say "Create Registration" and add a new method "createOrUpdateRegistration" without the need of ETag, or apply my patch and let this method be "create or update" as it works the same.

**Comment by guillaumelecerf** [comment]
Thanks.

**Comment by shiroko** [comment]
Sorry, I was wrong.
NotificationHub::updateRegistration was made for "create or update"API.

Thanks.

**Pull request merged**
